var files_dup =
[
    [ "advps.c", "advps_8c.html", "advps_8c" ],
    [ "vc_client_common.c", "vc__client__common_8c.html", "vc__client__common_8c" ],
    [ "vc_client_common.h", "vc__client__common_8h.html", "vc__client__common_8h" ],
    [ "vc_client_idle.c", "vc__client__idle_8c.html", "vc__client__idle_8c" ],
    [ "vc_client_idle.h", "vc__client__idle_8h.html", "vc__client__idle_8h" ],
    [ "vc_client_netdown.c", "vc__client__netdown_8c.html", "vc__client__netdown_8c" ],
    [ "vc_client_netdown.h", "vc__client__netdown_8h.html", "vc__client__netdown_8h" ],
    [ "vc_client_netup.c", "vc__client__netup_8c.html", "vc__client__netup_8c" ],
    [ "vc_client_netup.h", "vc__client__netup_8h.html", "vc__client__netup_8h" ],
    [ "vc_client_pause.c", "vc__client__pause_8c.html", "vc__client__pause_8c" ],
    [ "vc_client_pause.h", "vc__client__pause_8h.html", "vc__client__pause_8h" ],
    [ "vc_client_sync.c", "vc__client__sync_8c.html", "vc__client__sync_8c" ],
    [ "vc_client_sync.h", "vc__client__sync_8h.html", "vc__client__sync_8h" ],
    [ "vcom.h", "vcom_8h.html", "vcom_8h" ],
    [ "vcom_client.c", "vcom__client_8c.html", "vcom__client_8c" ],
    [ "vcom_debug.h", "vcom__debug_8h.html", "vcom__debug_8h" ],
    [ "vcom_load_sslcfg.h", "vcom__load__sslcfg_8h.html", "vcom__load__sslcfg_8h" ],
    [ "vcom_monitor.h", "vcom__monitor_8h.html", "vcom__monitor_8h" ],
    [ "vcom_monitor_dbg.h", "vcom__monitor__dbg_8h.html", "vcom__monitor__dbg_8h" ],
    [ "vcom_monitor_pre_stat.h", "vcom__monitor__pre__stat_8h.html", "vcom__monitor__pre__stat_8h" ],
    [ "vcom_proto.h", "vcom__proto_8h.html", "vcom__proto_8h" ],
    [ "vcom_proto_cmd.h", "vcom__proto__cmd_8h.html", null ],
    [ "vcom_proto_ioctl.h", "vcom__proto__ioctl_8h.html", "vcom__proto__ioctl_8h" ],
    [ "example.hpp", "example_8hpp.html", "example_8hpp" ],
    [ "subclass-example.hpp", "subclass-example_8hpp.html", [
      [ "SubclassExample", "class_my_library_1_1_subclass_example.html", "class_my_library_1_1_subclass_example" ]
    ] ],
    [ "adv_main.c", "adv__main_8c.html", "adv__main_8c" ],
    [ "adv_mmap.c", "adv__mmap_8c.html", "adv__mmap_8c" ],
    [ "adv_uart.c", "adv__uart_8c.html", "adv__uart_8c" ],
    [ "adv_uart.h", "adv__uart_8h.html", [
      [ "adv_uart_port", "structadv__uart__port.html", "structadv__uart__port" ]
    ] ],
    [ "advconf.h", "advconf_8h.html", "advconf_8h" ],
    [ "advioctl.h", "advioctl_8h.html", "advioctl_8h" ],
    [ "advtype.h", "advtype_8h.html", "advtype_8h" ],
    [ "advvcom.h", "advvcom_8h.html", "advvcom_8h" ],
    [ "adv_proc_fops.h", "adv__proc__fops_8h.html", null ],
    [ "adv_proc_ioctl.c", "adv__proc__ioctl_8c.html", "adv__proc__ioctl_8c" ],
    [ "adv_proc_ioctl.h", "adv__proc__ioctl_8h.html", "adv__proc__ioctl_8h" ],
    [ "ops_fault.c", "ops__fault_8c.html", null ],
    [ "ops_fault.h", "ops__fault_8h.html", null ],
    [ "adv_uart_init.h", "adv__uart__init_8h.html", null ],
    [ "adv_uart_set_termios.c", "adv__uart__set__termios_8c.html", null ],
    [ "adv_uart_set_termios.h", "adv__uart__set__termios_8h.html", null ],
    [ "advttyd.c", "advttyd_8c.html", "advttyd_8c" ],
    [ "advttyd.h", "advttyd_8h.html", "advttyd_8h" ],
    [ "vcom_inotf.c", "vcom__inotf_8c.html", "vcom__inotf_8c" ],
    [ "advlist.h", "advlist_8h.html", "advlist_8h" ],
    [ "jsmn.c", "jsmn_8c.html", "jsmn_8c" ],
    [ "jsmn.h", "jsmn_8h.html", "jsmn_8h" ],
    [ "jstree.c", "jstree_8c.html", "jstree_8c" ],
    [ "jstree.h", "jstree_8h.html", "jstree_8h" ],
    [ "jstree_read.h", "jstree__read_8h.html", "jstree__read_8h" ],
    [ "overload.h", "overload_8h.html", "overload_8h" ],
    [ "proc_tools.c", "proc__tools_8c.html", "proc__tools_8c" ],
    [ "proc_tools.h", "proc__tools_8h.html", "proc__tools_8h" ],
    [ "ssl_select.c", "ssl__select_8c.html", "ssl__select_8c" ],
    [ "ssl_select.h", "ssl__select_8h.html", "ssl__select_8h" ]
];