var hierarchy =
[
    [ "_client_info", "struct__client__info.html", null ],
    [ "_ioctl_data", "struct__ioctl__data.html", null ],
    [ "_t_treenode", "struct__t__treenode.html", null ],
    [ "_t_treenode_data", "struct__t__treenode__data.html", null ],
    [ "_TTYINFO", "struct___t_t_y_i_n_f_o.html", null ],
    [ "adv_port_att", "structadv__port__att.html", null ],
    [ "adv_port_info", "structadv__port__info.html", null ],
    [ "adv_uart_port", "structadv__uart__port.html", null ],
    [ "adv_vcom", "structadv__vcom.html", null ],
    [ "Example", "class_my_library_1_1_example.html", [
      [ "SubclassExample", "class_my_library_1_1_subclass_example.html", null ]
    ] ],
    [ "jsmn_parser", "structjsmn__parser.html", null ],
    [ "jsmntok_t", "structjsmntok__t.html", null ],
    [ "jstreeret", "structjstreeret.html", null ],
    [ "list_head", "structlist__head.html", null ],
    [ "ring_buf", "structring__buf.html", null ],
    [ "ssl_info", "structssl__info.html", null ],
    [ "ssl_pwd_data", "structssl__pwd__data.html", null ],
    [ "stk_vc", "structstk__vc.html", null ],
    [ "vc_attach_data", "structvc__attach__data.html", null ],
    [ "vc_attach_hflow", "structvc__attach__hflow.html", null ],
    [ "vc_attach_lctrl", "structvc__attach__lctrl.html", null ],
    [ "vc_attach_param", "structvc__attach__param.html", null ],
    [ "vc_attach_uint", "structvc__attach__uint.html", null ],
    [ "vc_attr", "structvc__attr.html", null ],
    [ "vc_monitor", "structvc__monitor.html", null ],
    [ "vc_ops", "structvc__ops.html", null ],
    [ "vc_proto_hdr", "structvc__proto__hdr.html", null ],
    [ "vc_proto_packet", "structvc__proto__packet.html", null ],
    [ "vc_ssl_cfg", "structvc__ssl__cfg.html", null ],
    [ "wait_event", "structwait__event.html", null ]
];