
name: 'build deb-package'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-debs-dpkg
        # You may pin to the exact commit or the version.
        # uses: shumailaahmed/build-deb-action@11058815a9e1bb20262bcd64df40df074825a77c
        uses: shumailaahmed/build-deb-action@v1.0.2
        with:
          # Package name of debian package.
          package: advvcom-2.3.4
          # Directory of release files.
          package_root: advvcom
          # Package maintainer name.
          maintainer: tsaiyuyan
          # Package version.
